name: Chat app build and tests
run-name: ${{ github.actor }} is running actions 🚀
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:    
  eslint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: npm install
      - name: Running ESLint on Server🔎
        run:  | 
          cd packages/api
          npm run eslint
      - name: Running ESLint on Client 🔎
        run:  | 
          cd packages/client
          npm run eslint
      - run: echo "${{job.name}} job status ${{ job.status }}."
  
  test_job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checking out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - name: Running client tests 🔎
        run:  | 
          cd packages/client
          npm run test
      - name: Running server tests 🔎
        run:  | 
          cd packages/api
          npm run test
