name: Chat app build and tests
run-name: ${{ github.actor }} is running actions 🚀
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{job.name}} job status ${{ job.status }}."
      
  eslint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: npm install
      - name: Running ESLint on Server🔎
        run:  | 
          cd packages/api
          npm run eslint
      - name: Running ESLint on Client 🔎
        run:  | 
          cd packages/client
          npm run eslint
      - run: echo "${{job.name}} job status ${{ job.status }}."
  
  test_job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checking out repository code
        uses: actions/checkout@v3
      - run: docker compose up --build
      - run: npm run build --if-present
      - name: Running client tests 🔎
        run:  docker exec ts-chatapp-client npm test -w packages/client
      - name: Running server tests 🔎
        run:  docker exec ts-chatapp-api npm test -w packages/api
