name: Chat app build and tests
run-name: ${{ github.actor }} is running actions 🚀
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{job.name}} job status ${{ job.status }}."
      
  eslint_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository code
        uses: actions/checkout@v3
      - name: Installing dependencies
        run: npm install
      - name: Running ESLint on Server🔎
        run:  | 
          cd packages/api
          npm run eslint
      - name: Running ESLint on Client 🔎
        run:  | 
          cd packages/client
          npm run eslint
      - run: echo "${{job.name}} job status ${{ job.status }}."
  
  test_job: 
    runs-on: ubuntu-latest
    services: 
      postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        env: 
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: chatappdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps: 
      - name: Checking out repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Running client tests 🔎
        run:  npm run test -w packages/client
      - name: Running server tests 🔎
        run:  npm run test -w packages/client
