name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing GitHub Actions 🚀
on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: npm install
      - name: Running ESLint on Server
        run:  | 
          cd packages/api
          npm run eslint
      - name: Running ESLint on Client
        run: echo "Running ESLint on Client"
      - run: echo "${{job.name}} job status ${{ job.status }}."
  
  test: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Running client unit tests
        run:  | 
          cd packages/client
          npm run test
      - run: echo "${{job.name}} job status ${{ job.status }}."
    
